### ISSUE TITLE
TS new 2.X version not working

### ISSUE THREAD

**Issue by ssimk0** [dropzone-ui/dropzone-ui#49]
Hi,
not sure what you change after version 2.X but I install the new version of dropzone and its start complaning that I should install @types/dropzone-ui, but it looks like that something is wrong. 
```
Could not find a declaration file for module 'dropzone-ui'. '/xxx/node_modules/dropzone-ui/build/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/dropzone-ui` if it exists or add a new declaration (.d.ts) file containing `declare module 'dropzone-ui';`
```
When I open the npm_modules the structure not look right I add the screenshot of that. Could you help me with that ?

![image](https://user-images.githubusercontent.com/44171355/135494824-a29f4d28-3123-4ad4-98e4-f561357ffba7.png)

**Comment by JinSSJ3** [comment]
Hi @ssimk0 , thanks for the comment. There was a problem on the build process we didn't notice. This was produced due to oneof the dependencies that makes the build file and didn't make the type definitions. 
Really sorry about that.
Could you please reinstall the package? There is a new version (2.1.1) that fixes this problem.

**Comment by ssimk0** [comment]
Hi,
@JinSSJ3 thanks new version is working :+1:
